### ISSUE TITLE
Read .log.gz Files and Show JSON

### ISSUE THREAD

**Issue by PBhadoo** [G4brym/R2-Explorer#20]
Log Push generates files like

20230715T025607Z_20230715T025637Z_9d3b03d0.log.gz

it contains JSON data. Allow reading in Explorer so can easily check logs.

**Comment by G4brym** [comment]
can you upload an example log push here?

**Comment by PBhadoo** [comment]
> can you upload an example log push here?
[20230715T025607Z_20230715T025637Z_9d3b03d0.log.gz](https://github.com/G4brym/R2-Explorer/files/12447136/20230715T025607Z_20230715T025637Z_9d3b03d0.log.gz)

**Comment by G4brym** [comment]
Hey @PBhadoo 
Thanks for suggesting this very good feature, I've added support for opening log push files in the new v1.0.0 release
[Here is an example in the demo R2 Explorer](https://demo.r2explorer.dev/storage/example-1/IA==/ZXhhbXBsZV9jbG91ZGZsYXJlX2xvZ3B1c2gubG9nLmd6)

Migration guide to 1.0.0 [available here](https://r2explorer.dev/guides/migrating-to-1.0/)
