### ISSUE TITLE
Support Presigned URLs

### ISSUE THREAD

**Issue by jarylc** [G4brym/R2-Explorer#21]
Possible enhancement to simulate "share" functionality of Google Drive

https://developers.cloudflare.com/r2/api/s3/presigned-urls/

**Comment by G4brym** [comment]
Hey @jarylc presigned urls are only possible using the s3 api, and this project only uses the workers api
adding that in this project would require users to generate an api key and secret and define that configuration files

File sharing is planned for the future to work like google drive, when you open the url the file preview pops up the the selected file

**Comment by jarylc** [comment]
I do believe I saw Workers API supporting Presigned URL generation though

https://developers.cloudflare.com/r2/api/s3/presigned-urls/

**Comment by G4brym** [comment]
Hey @jarylc i've just added a `get sharable link` to files:
![image](https://github.com/G4brym/R2-Explorer/assets/5445926/890f9dc1-7115-42f0-b66f-d0cdefe10acc)

Then when a user opens that link, the file preview pops up automatically

**Comment by jarylc** [comment]
I'm looking for a direct download/upload with R2 via a Signed URL vs having to proxy through a worker still, I'll check internally if there are plans to add functionality to easily generate Signed URLs via Workers.
