### ISSUE TITLE
error publish cloudflare worker

### ISSUE THREAD

**Issue by tawayaka** [G4brym/R2-Explorer#4]
i am trying to publish to worker but getting error:
`Built successfully, built project size is 655 KiB.
Error: Something went wrong with the request to Cloudflare...
No event handlers were registered. This script does nothing.
 [API code: 10021]`
![image](https://user-images.githubusercontent.com/30314539/206856009-97b59973-b889-4560-a17f-f845080672d6.png)

**Comment by G4brym** [comment]
Hey @tawayaka can you confirm which version of wrangler you are running with the command `wrangler --version`

**Comment by tawayaka** [comment]
hmm i know where is my error i am using wrangler v1 i will update to v2 thank you!

**Comment by G4brym** [comment]
yeah, running this `npm uninstall -g @cloudflare/wrangler` should be enough to fix your issue, as wrangler2 was already installed when you run `npm install` with this project

**Comment by tawayaka** [comment]
> yeah, running this `npm uninstall -g @cloudflare/wrangler` should be enough to fix your issue, as wrangler2 was already installed when you run `npm install` with this project

thank you very much, but i have 1 new problem:
i fixed 'readonly: false' but why i can't download my file?, i can upload my file

**Comment by G4brym** [comment]
do you see any errors in the browser console? what is the file size?

**Comment by tawayaka** [comment]
> bạn có thấy bất kỳ lỗi nào trong bảng điều khiển trình duyệt không? kích thước tập tin là gì?

I don't see any error but when I click it just shows:
![image](https://user-images.githubusercontent.com/30314539/206866934-4bbf5ba0-7a8f-40e8-a9e4-70b3592fd695.png)

the file size is less than 50mb, and the file extension is .flac, .zip. it can display image files

**Comment by npullen2000** [comment]
You have to right click the file you want to download.

**Comment by G4brym** [comment]
There was an issue in the download button on the latest version, and I've just fixed it
All you need to do, is to upgrade to the newer version with this command `npm install --save r2-explorer@latest` and then publish the worker again

Downloading a big file, might take some time to show up in the browser, because there is no loading message yet, i will try to add that soon

**Comment by tawayaka** [comment]
> There was an issue in the download button on the latest version, and I've just fixed it All you need to do, is to upgrade to the newer version with this command `npm install --save r2-explorer@latest` and then publish the worker again
> 
> Downloading a big file, might take some time to show up in the browser, because there is no loading message yet, i will try to add that soon

it worked, thank you so much for helping me.

**Comment by G4brym** [comment]
the share button is not implemented yet, it will be soon

**Comment by tawayaka** [comment]
> the share button is not implemented yet, it will be soon

sorry but download is currently crashing for video and image files, when i download from r2-explore it crashes 
![image](https://user-images.githubusercontent.com/30314539/207628591-0833cb4b-9a94-4705-8c63-4d6d86dc3149.png)

 i download from cloudflare homepage it plays fine

**Comment by G4brym** [comment]
The problem should be fixed now, update to the latest version to get the fix with this command `npm install --save r2-explorer@latest` and publish the worker again

Thank you for sharing this issues, and let me know if you find more 😄

**Comment by tawayaka** [comment]
> The problem should be fixed now, update to the latest version to get the fix with this command `npm install --save r2-explorer@latest` and publish the worker again
> 
> Thank you for sharing this issues, and let me know if you find more 😄

thank you very much
