### ISSUE TITLE
`Upload Folders` works differently

### ISSUE THREAD

**Issue by imjlk** [G4brym/R2-Explorer#43]
When I upload folder B from the `/bucket/A`, the path `/bucket/A/B` will be created, but the files in folder B will be in the A path and there will be nothing in `/bucket/A/B`.

I haven't tested this on other environments yet,
I'm on MacOS 13.5.1 (ARM), using chrome 116.0.5845.179

**Comment by ebbo-DO** [comment]
Currently experiencing this as well. Folders don't copy reclusively. The initial sub-folder is created but all of its contents are uploaded to the root..

**Comment by G4brym** [comment]
Hey there, i've just published a fix for that bug, you should now be able to correctly upload nested folders, without needning to update your r2-explorer instance
Let me know if you find anything else

**Comment by ebbo-DO** [comment]
@G4brym Confirmed!
