### ISSUE TITLE
 Fix folder upload with inner folders - breaks uploading to the root folder

### ISSUE THREAD

**Issue by audiovention** [G4brym/R2-Explorer#47]
this commit 
https://github.com/G4brym/R2-Explorer/commit/519ebd4f7fa56f612867815a13c322a9815b69e5
seems to add "/" to every file uploaded, so basically it's impossible to upload to the root folder of a bucket. 
What's more "/" doesn't seem to be a super valid folder name so you can't see the uploaded files in r2explorer either

**Comment by G4brym** [comment]
Hey @audiovention, thanks for reporting this, I just deployed a fix for this
If you are using the default dashboard url it should work now
