### ISSUE TITLE
[Bug] account_id in deploy via GitHub to CF Workers

### ISSUE THREAD

**Issue by fernandodilland** [G4brym/R2-Explorer#52]
When trying to deploy directly from Github to Cloudflare Workers, When using a Cloudflare account with multiple accounts, it is not defined which account to use, the error appears:

```
[ERROR] More than one account available but unable to select one in non-interactive mode.
  
    Please set the appropriate `account_id` in your `wrangler.toml` file.
    Available accounts are (`<name>`: `<account_id>`):
      `EXAMPLE-NAME1`: `EXAMPLE-ID1`
      `EXAMPLE-NAME2`: `EXAMPLE-ID2`
      `EXAMPLE-NAME3: `EXAMPLE-ID3`
      ...
```

**Comment by maharjanmilan** [comment]
I have the same issue as well

**Comment by G4brym** [comment]
Hey there, i've just pushed a new commit and adds support for defining the account id.
Create a new secret with the name `CLOUDFLARE_ACCOUNT_ID` and the desired Cloudflare account id. Then sync the fork again.
Let me know if this worked for you

**Comment by fernandodilland** [comment]
I have tried it and it works great! @G4brym

**Comment by maharjanmilan** [comment]
wow thanks for the quick update ♥️
