### ISSUE TITLE
Error: missing field `type`

### ISSUE THREAD

**Issue by Bad3r** [G4brym/R2-Explorer#6]
Following the instructions; when running `wrangler publish` it returns an error due to the missing field 'type'
```sh
❯ wrangler publish  
Error: missing field `type`
```

**Comment by G4brym** [comment]
Hey @Bad3r  can you confirm which version of wrangler you are running with the command `wrangler --version`
Make sure you are running version 2.x

**Comment by Bad3r** [comment]
Thank you I was using wrangler 1.x. It worked after using wrangelr2
